package com.archermind.schedule.Events;

public enum EventTypes {
	LOCAL_SCHEDULE_UPDATE, CONTACT_SYNC_SUCCESS, CONTACT_SYNC_CANCEL, CONTACT_SYNC_FAILED, SERVICE_TIP_ON, SERVICE_TIP_OFF, COOKIE_ERROR, LOGIN_SUCCESS, TELEPHONE_BIND_SUCCESS, IMSI_CHANGED, ADD_FRIEND
}
